# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'basicgui.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GUI(object):
    def setupUi(self, GUI):
        GUI.setObjectName("GUI")
        GUI.setEnabled(True)
        GUI.resize(703, 550)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GUI.sizePolicy().hasHeightForWidth())
        GUI.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(GUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.modelLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modelLabel.sizePolicy().hasHeightForWidth())
        self.modelLabel.setSizePolicy(sizePolicy)
        self.modelLabel.setObjectName("modelLabel")
        self.horizontalLayout_2.addWidget(self.modelLabel)
        self.modelLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.modelLineEdit.setObjectName("modelLineEdit")
        self.horizontalLayout_2.addWidget(self.modelLineEdit)
        self.modelBrowseButton = QtWidgets.QPushButton(self.centralwidget)
        self.modelBrowseButton.setObjectName("modelBrowseButton")
        self.horizontalLayout_2.addWidget(self.modelBrowseButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.dividerLine = QtWidgets.QFrame(self.centralwidget)
        self.dividerLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.dividerLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.dividerLine.setObjectName("dividerLine")
        self.verticalLayout.addWidget(self.dividerLine)
        self.inputLabel = QtWidgets.QLabel(self.centralwidget)
        self.inputLabel.setObjectName("inputLabel")
        self.verticalLayout.addWidget(self.inputLabel)
        self.burnList = QtWidgets.QListView(self.centralwidget)
        self.burnList.setObjectName("burnList")
        self.verticalLayout.addWidget(self.burnList)
        self.predictButton = QtWidgets.QPushButton(self.centralwidget)
        self.predictButton.setObjectName("predictButton")
        self.verticalLayout.addWidget(self.predictButton)
        self.display = QtWidgets.QLabel(self.centralwidget)
        self.display.setMinimumSize(QtCore.QSize(0, 300))
        self.display.setObjectName("display")
        self.verticalLayout.addWidget(self.display)
        self.horizontalLayout.addLayout(self.verticalLayout)
        GUI.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(GUI)
        self.toolBar.setObjectName("toolBar")
        GUI.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionN = QtWidgets.QAction(GUI)
        self.actionN.setCheckable(True)
        self.actionN.setChecked(True)
        self.actionN.setObjectName("actionN")
        self.actionKg = QtWidgets.QAction(GUI)
        self.actionKg.setCheckable(True)
        self.actionKg.setObjectName("actionKg")
        self.actionLbs = QtWidgets.QAction(GUI)
        self.actionLbs.setCheckable(True)
        self.actionLbs.setObjectName("actionLbs")
        self.actionOpenCal = QtWidgets.QAction(GUI)
        self.actionOpenCal.setShortcut("")
        self.actionOpenCal.setObjectName("actionOpenCal")
        self.actionSaveCal = QtWidgets.QAction(GUI)
        self.actionSaveCal.setObjectName("actionSaveCal")
        self.actionSaveCalAs = QtWidgets.QAction(GUI)
        self.actionSaveCalAs.setObjectName("actionSaveCalAs")
        self.actionSave_2 = QtWidgets.QAction(GUI)
        self.actionSave_2.setObjectName("actionSave_2")
        self.actionOpenRec = QtWidgets.QAction(GUI)
        self.actionOpenRec.setObjectName("actionOpenRec")
        self.actionSaveRec = QtWidgets.QAction(GUI)
        self.actionSaveRec.setObjectName("actionSaveRec")
        self.actionSaveRecAs = QtWidgets.QAction(GUI)
        self.actionSaveRecAs.setObjectName("actionSaveRecAs")
        self.actionExportSnippet = QtWidgets.QAction(GUI)
        self.actionExportSnippet.setObjectName("actionExportSnippet")
        self.modelLabel.setBuddy(self.modelBrowseButton)

        self.retranslateUi(GUI)
        QtCore.QMetaObject.connectSlotsByName(GUI)

    def retranslateUi(self, GUI):
        _translate = QtCore.QCoreApplication.translate
        GUI.setWindowTitle(_translate("GUI", "Hot Topic"))
        self.modelLabel.setText(_translate("GUI", "Model:"))
        self.modelLineEdit.setText(_translate("GUI", "None set..."))
        self.modelBrowseButton.setText(_translate("GUI", "Browse..."))
        self.inputLabel.setText(_translate("GUI", "Inputs:"))
        self.predictButton.setText(_translate("GUI", "Predict!"))
        self.display.setText(_translate("GUI", "Display"))
        self.toolBar.setWindowTitle(_translate("GUI", "toolBar"))
        self.actionN.setText(_translate("GUI", "N"))
        self.actionKg.setText(_translate("GUI", "kg"))
        self.actionLbs.setText(_translate("GUI", "lbs"))
        self.actionOpenCal.setText(_translate("GUI", "Open..."))
        self.actionSaveCal.setText(_translate("GUI", "Save"))
        self.actionSaveCalAs.setText(_translate("GUI", "Save As..."))
        self.actionSave_2.setText(_translate("GUI", "Save"))
        self.actionOpenRec.setText(_translate("GUI", "Open..."))
        self.actionSaveRec.setText(_translate("GUI", "Save"))
        self.actionSaveRecAs.setText(_translate("GUI", "Save As..."))
        self.actionExportSnippet.setText(_translate("GUI", "Export Snippet..."))
